"""

Revision ID: d2dd9b3e6220
Revises: e9f5d5aa50c0
Create Date: 2025-05-29 06:58:20.931646+03:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d2dd9b3e6220"
down_revision: Union[str, None] = "e9f5d5aa50c0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "folders",
        "title",
        existing_type=sa.VARCHAR(length=30),
        type_=sa.String(length=60),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "folders",
        "title",
        existing_type=sa.String(length=60),
        type_=sa.VARCHAR(length=30),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
