"""nullable file description.


Revision ID: 0712054afb72
Revises: 6e2796ed43be
Create Date: 2025-09-26 01:09:29.666217+03:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0712054afb72"
down_revision: Union[str, None] = "6e2796ed43be"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("files", "description", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("files", "description", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
