"""

Revision ID: f408ac85ce52
Revises: c57eb835c8b4
Create Date: 2025-05-19 11:53:01.883668+03:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f408ac85ce52"
down_revision: Union[str, None] = "c57eb835c8b4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("folders", sa.Column("parent_id", sa.Uuid(), nullable=True))
    op.create_index(
        op.f("ix_folders_parent_id"), "folders", ["parent_id"], unique=False
    )
    op.create_foreign_key(None, "folders", "folders", ["parent_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "folders", type_="foreignkey")
    op.drop_index(op.f("ix_folders_parent_id"), table_name="folders")
    op.drop_column("folders", "parent_id")
    # ### end Alembic commands ###
