"""

Revision ID: 41853f21d9ce
Revises: 84d645406e6f
Create Date: 2025-05-21 12:52:00.327695+03:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "41853f21d9ce"
down_revision: Union[str, None] = "84d645406e6f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "plagiarism_checks", "chunks_found", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "plagiarism_checks", "matches_found", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "plagiarism_checks",
        "average_chunks_similarity",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "plagiarism_checks",
        "average_chunks_similarity",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
    )
    op.alter_column(
        "plagiarism_checks", "matches_found", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "plagiarism_checks", "chunks_found", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###
