"""

Revision ID: f2632b84cad6
Revises: 11b0a3f62402
Create Date: 2025-05-20 11:54:27.586347+03:00

"""

import pgvector
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f2632b84cad6"
down_revision: Union[str, None] = "11b0a3f62402"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "document_chunks",
        sa.Column("vector", pgvector.sqlalchemy.vector.VECTOR(), nullable=True),
    )
    op.create_index(
        op.f("ix_document_chunks_vector"), "document_chunks", ["vector"], unique=False
    )
    op.drop_column("document_chunks", "hash")
    op.drop_column("document_chunks", "content")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "document_chunks",
        sa.Column("content", sa.TEXT(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "document_chunks",
        sa.Column("hash", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_index(op.f("ix_document_chunks_vector"), table_name="document_chunks")
    op.drop_column("document_chunks", "vector")
    # ### end Alembic commands ###
