"""

Revision ID: f595cec67f38
Revises: a36a509f0758
Create Date: 2025-05-17 16:50:04.702387+03:00

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "f595cec67f38"
down_revision: Union[str, None] = "a36a509f0758"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
