"""

Revision ID: c57eb835c8b4
Revises: 44295238cd2a
Create Date: 2025-05-19 11:40:13.128909+03:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c57eb835c8b4"
down_revision: Union[str, None] = "44295238cd2a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("folders", sa.Column("title", sa.String(length=30), nullable=False))
    op.drop_index("ix_folders_name", table_name="folders")
    op.create_index(op.f("ix_folders_title"), "folders", ["title"], unique=False)
    op.drop_column("folders", "name")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "folders",
        sa.Column("name", sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    )
    op.drop_index(op.f("ix_folders_title"), table_name="folders")
    op.create_index("ix_folders_name", "folders", ["name"], unique=False)
    op.drop_column("folders", "title")
    # ### end Alembic commands ###
