"""

Revision ID: 601b5e3a5a63
Revises: a3e2e83d103d
Create Date: 2025-03-15 12:39:36.875062+03:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "601b5e3a5a63"
down_revision: Union[str, None] = "a3e2e83d103d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("plagiarism_results", "completed_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "plagiarism_results",
        sa.Column(
            "completed_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
    )
    # ### end Alembic commands ###
