"""

Revision ID: 05f578d37216
Revises: 5e0c6e3834c6
Create Date: 2025-05-19 15:26:53.796317+03:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "05f578d37216"
down_revision: Union[str, None] = "5e0c6e3834c6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("documents", sa.Column("is_indexed", sa.Boolean(), nullable=False))
    op.add_column(
        "documents", sa.Column("last_indexed_at", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("documents", "last_indexed_at")
    op.drop_column("documents", "is_indexed")
    # ### end Alembic commands ###
