"""

Revision ID: 9953b02c6bd4
Revises: 04b7493600d3
Create Date: 2025-05-29 07:55:10.631991+03:00

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "9953b02c6bd4"
down_revision: Union[str, None] = "04b7493600d3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "document_chunks_document_id_fkey", "document_chunks", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "document_chunks",
        "documents",
        ["document_id"],
        ["id"],
        ondelete="cascade",
    )
    op.drop_constraint("documents_file_id_fkey", "documents", type_="foreignkey")
    op.drop_constraint("documents_folder_id_fkey", "documents", type_="foreignkey")
    op.create_foreign_key(
        None, "documents", "folders", ["folder_id"], ["id"], ondelete="cascade"
    )
    op.create_foreign_key(
        None, "documents", "files", ["file_id"], ["id"], ondelete="cascade"
    )
    op.drop_constraint(
        "plagiarism_checks_document_id_fkey", "plagiarism_checks", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "plagiarism_checks",
        "documents",
        ["document_id"],
        ["id"],
        ondelete="cascade",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "plagiarism_checks", type_="foreignkey")
    op.create_foreign_key(
        "plagiarism_checks_document_id_fkey",
        "plagiarism_checks",
        "documents",
        ["document_id"],
        ["id"],
    )
    op.drop_constraint(None, "documents", type_="foreignkey")
    op.drop_constraint(None, "documents", type_="foreignkey")
    op.create_foreign_key(
        "documents_folder_id_fkey", "documents", "folders", ["folder_id"], ["id"]
    )
    op.create_foreign_key(
        "documents_file_id_fkey", "documents", "files", ["file_id"], ["id"]
    )
    op.drop_constraint(None, "document_chunks", type_="foreignkey")
    op.create_foreign_key(
        "document_chunks_document_id_fkey",
        "document_chunks",
        "documents",
        ["document_id"],
        ["id"],
    )
    # ### end Alembic commands ###
