"""

Revision ID: 7d0f811097b5
Revises: a8e8055547a2
Create Date: 2025-05-20 09:45:18.308752+03:00

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "7d0f811097b5"
down_revision: Union[str, None] = "a8e8055547a2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "unique_document_author_title", "documents", ["author_id", "title"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("unique_document_author_title", "documents", type_="unique")
    # ### end Alembic commands ###
