"""Removed 'indexed_at' and 'indexed' from 'Document' model.


Revision ID: 6e2796ed43be
Revises: dd3ba30bf465
Create Date: 2025-09-25 23:08:26.233096+03:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6e2796ed43be"
down_revision: Union[str, None] = "dd3ba30bf465"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("documents", "idexed_at")
    op.drop_column("documents", "is_indexed")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "documents",
        sa.Column("is_indexed", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "documents",
        sa.Column(
            "idexed_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
    )
    # ### end Alembic commands ###
