"""

Revision ID: a8e8055547a2
Revises: 7fa4a98cf677
Create Date: 2025-05-20 07:41:37.048767+03:00

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "a8e8055547a2"
down_revision: Union[str, None] = "7fa4a98cf677"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
