"""

Revision ID: 44295238cd2a
Revises: 280c17d51d09
Create Date: 2025-05-19 10:41:45.139402+03:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "44295238cd2a"
down_revision: Union[str, None] = "280c17d51d09"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "documents_authors",
        sa.Column("description", sa.String(length=255), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("documents_authors", "description")
    # ### end Alembic commands ###
