"""

Revision ID: 04b7493600d3
Revises: d2dd9b3e6220
Create Date: 2025-05-29 06:59:21.402408+03:00

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '04b7493600d3'
down_revision: Union[str, None] = 'd2dd9b3e6220'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
