"""

Revision ID: 5e0c6e3834c6
Revises: 4198c54e93e3
Create Date: 2025-05-19 14:24:50.533027+03:00

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '5e0c6e3834c6'
down_revision: Union[str, None] = '4198c54e93e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('folders_parent_id_fkey', 'folders', type_='foreignkey')
    op.create_foreign_key(None, 'folders', 'folders', ['parent_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'folders', type_='foreignkey')
    op.create_foreign_key('folders_parent_id_fkey', 'folders', 'folders', ['parent_id'], ['id'])
    # ### end Alembic commands ###
