"""Description nullable.

Revision ID: dd3ba30bf465
Revises: 0d42db74fb8b
Create Date: 2025-09-20 08:13:09.942859+03:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dd3ba30bf465"
down_revision: Union[str, None] = "0d42db74fb8b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "folders", "description", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "folders", "description", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    # ### end Alembic commands ###
