"""

Revision ID: 84d645406e6f
Revises: 5d2b80d6edf5
Create Date: 2025-05-21 12:49:57.296594+03:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "84d645406e6f"
down_revision: Union[str, None] = "5d2b80d6edf5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "plagiarism_checks", sa.Column("chunks_found", sa.Integer(), nullable=False)
    )
    op.add_column(
        "plagiarism_checks", sa.Column("matches_found", sa.Integer(), nullable=False)
    )
    op.add_column(
        "plagiarism_checks",
        sa.Column("average_chunks_similarity", sa.Float(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("plagiarism_checks", "average_chunks_similarity")
    op.drop_column("plagiarism_checks", "matches_found")
    op.drop_column("plagiarism_checks", "chunks_found")
    # ### end Alembic commands ###
