"""

Revision ID: 11b0a3f62402
Revises: 7d0f811097b5
Create Date: 2025-05-20 10:36:26.718930+03:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "11b0a3f62402"
down_revision: Union[str, None] = "7d0f811097b5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("unique_document_file_id", "documents", ["file_id"])
    op.add_column("files", sa.Column("created_by_id", sa.Uuid(), nullable=False))
    op.drop_index("ix_files_owner_id", table_name="files")
    op.create_index(
        op.f("ix_files_created_by_id"), "files", ["created_by_id"], unique=False
    )
    op.drop_constraint("files_owner_id_fkey", "files", type_="foreignkey")
    op.create_foreign_key(None, "files", "users", ["created_by_id"], ["id"])
    op.drop_column("files", "owner_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "files", sa.Column("owner_id", sa.UUID(), autoincrement=False, nullable=False)
    )
    op.drop_constraint(None, "files", type_="foreignkey")
    op.create_foreign_key("files_owner_id_fkey", "files", "users", ["owner_id"], ["id"])
    op.drop_index(op.f("ix_files_created_by_id"), table_name="files")
    op.create_index("ix_files_owner_id", "files", ["owner_id"], unique=False)
    op.drop_column("files", "created_by_id")
    op.drop_constraint("unique_document_file_id", "documents", type_="unique")
    # ### end Alembic commands ###
