"""

Revision ID: 7fa4a98cf677
Revises: 05f578d37216
Create Date: 2025-05-20 07:36:25.637705+03:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7fa4a98cf677"
down_revision: Union[str, None] = "05f578d37216"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("documents", sa.Column("folder_id", sa.Uuid(), nullable=False))
    op.create_index(
        op.f("ix_documents_folder_id"), "documents", ["folder_id"], unique=False
    )
    op.create_foreign_key(None, "documents", "folders", ["folder_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "documents", type_="foreignkey")
    op.drop_index(op.f("ix_documents_folder_id"), table_name="documents")
    op.drop_column("documents", "folder_id")
    # ### end Alembic commands ###
