"""Init...

Revision ID: bcc32048dedc
Revises:
Create Date: 2025-03-13 21:18:48.013831+03:00

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "bcc32048dedc"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
